/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradlex.buildparameters.poc.sample.teama;

import org.gradle.api.provider.Provider;

/**
 * Stands in for a type <em>published by another team</em> (e.g. {@code com.teama.jvm:jvm-parameters}).
 *
 * <p>It is a normal, hand-authored interface with a stable identity — not generated by this engine. Both
 * the generated build-parameter accessors and any build logic compiled against it (see {@link JvmReport})
 * share this exact type, which is what makes cross-plugin composition work.</p>
 */
public interface JavaDistribution {
    Provider<String> getVersion();

    Provider<String> getVendor();
}
