/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradlex.buildparameters.poc.runtime;

import org.gradle.api.Transformer;
import org.gradle.api.provider.Provider;
import org.gradle.api.provider.ProviderFactory;

import java.io.Serializable;

/**
 * Runtime support invoked by the generated accessor classes.
 *
 * <p>The generated bytecode never contains any logic of its own beyond a single {@code invokestatic}
 * into the methods below. Keeping the logic here (normal, javac-compiled code) keeps the ASM emitter
 * trivial and, crucially, keeps the provider chain made of <em>named, {@link Serializable}</em> types so
 * the resulting {@link Provider} survives Configuration Cache store/load.</p>
 *
 * <p>This class lives in the plugin jar. Because a settings plugin's classpath is {@code export()}ed into
 * the settings {@code ClassLoaderScope}, it is visible to every descendant scope — including the build
 * script scopes and the task-execution classpath — which is what lets the serialized providers reference
 * {@link StringToInteger}/{@link StringToBoolean} at execution time.</p>
 */
public final class Params {

    private Params() {
    }

    public static Provider<String> string(ProviderFactory providers, String key, String defaultValue) {
        Provider<String> value = providers.gradleProperty(key);
        return defaultValue == null ? value : value.orElse(defaultValue);
    }

    public static Provider<Integer> integer(ProviderFactory providers, String key, Integer defaultValue) {
        Provider<Integer> value = providers.gradleProperty(key).map(new StringToInteger());
        return defaultValue == null ? value : value.orElse(defaultValue);
    }

    public static Provider<Boolean> bool(ProviderFactory providers, String key, Boolean defaultValue) {
        Provider<Boolean> value = providers.gradleProperty(key).map(new StringToBoolean());
        return defaultValue == null ? value : value.orElse(defaultValue);
    }

    /**
     * A named, serializable {@link Transformer} (as opposed to {@code Integer::valueOf}, whose synthetic
     * lambda class would not be cleanly serializable by the Configuration Cache).
     */
    public static final class StringToInteger implements Transformer<Integer, String>, Serializable {
        private static final long serialVersionUID = 1L;

        @Override
        public Integer transform(String s) {
            return Integer.valueOf(s.trim());
        }
    }

    public static final class StringToBoolean implements Transformer<Boolean, String>, Serializable {
        private static final long serialVersionUID = 1L;

        @Override
        public Boolean transform(String s) {
            return Boolean.valueOf(s.trim());
        }
    }
}
