/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradlex.buildparameters.poc.schema;

/**
 * A group type whose accessor class is <em>not</em> generated by this engine but supplied by a published
 * artifact (typically a different team's plugin/library). This is what enables cross-plugin composition:
 * the shared type identity lives in a real artifact, so both the generated accessors and any build logic
 * compiled against it interoperate.
 *
 * <p>It names:</p>
 * <ul>
 *     <li>{@code interfaceFqcn} — the accessor type the generated getter returns, e.g.
 *         {@code com.teama.jvm.JavaDistribution};</li>
 *     <li>{@code factoryOwnerFqcn} + {@code factoryMethod} — a static factory
 *         {@code Type from(ProviderFactory providers, String keyPrefix)} that builds an instance bound to
 *         the mount's key prefix.</li>
 * </ul>
 *
 * <p>The owning artifact must be on the settings/plugin classpath (an ancestor of the scope the generated
 * accessors are exported into), exactly like this engine's own runtime helper.</p>
 */
public final class ExternalGroupType {
    private final String interfaceFqcn;
    private final String factoryOwnerFqcn;
    private final String factoryMethod;

    public ExternalGroupType(String interfaceFqcn, String factoryOwnerFqcn, String factoryMethod) {
        this.interfaceFqcn = interfaceFqcn;
        this.factoryOwnerFqcn = factoryOwnerFqcn;
        this.factoryMethod = factoryMethod;
    }

    public String getInterfaceFqcn() {
        return interfaceFqcn;
    }

    public String getInterfaceInternalName() {
        return interfaceFqcn.replace('.', '/');
    }

    public String getFactoryOwnerInternalName() {
        return factoryOwnerFqcn.replace('.', '/');
    }

    public String getFactoryMethod() {
        return factoryMethod;
    }
}
